dir: generators
packageJson: package.json
articles:
  - Overview: README.md
  - App Generator Technologies: generators/app/README.md
  - App Mixin Modules: generators/app/templates/plugins/README.md
  - Available Generators: GENERATORS.md
